### ISSUE TITLE
Format data output to client specifications

### ISSUE THREAD

**Issue by adam-s** [adam-s/trolley-tracker#1]
Can you name this project "trolley-tracker" and rename anything else to trolley or trolleys?

How do I send the data from the tracker to you? (Ex: http://trolly-tracker.herokuapp.com/api/post)? Please put information in the GitHub wiki for your project if possible.

Can you return the JSON data in this format? (From http://trolly-tracker.herokuapp.com/api/trollies)
```
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          "25.7903",
          "-80.3738"
        ]
      },
      "properties": {
        "lat": "25.7903",
        "lon": "-80.3738",
        "bustime": "2016-03-06 17:17:39",
        "speed": "0.23",
        "deviceid": "1"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          "25.5774",
          "-80.3394"
        ]
      },
      "properties": {
        "lat": "25.5774",
        "lon": "-80.3394",
        "bustime": "2016-03-06 18:55:06",
        "speed": "0.03",
        "deviceid": "2"
      }
    }
  ]
}
```

**Comment by qtrandev** [comment]
The output you're returning is:
{
"status": "success",
"data": {
  "type": "FeatureCollection",
  "features": [
  {

All my clients are expecting this data:
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",

Is  it possible to produce this JSON or is there some server limitation?

**Comment by qtrandev** [comment]
Note that "deviceid" is all lowercase, not deviceId.
It's looking good though, I might be sending in data soon to that POST interface.

**Comment by adam-s** [comment]
Is there no way to take the `data` object from the incoming request and put it in a different variable? I constructed it this way as a best practice since knowing the nature of errors can be passed to the end user or a developer.

For example, from some code I found in your repository, the RecordSet is on the data object.
````
function init() {
  angular.module('transitApp', []).controller('transitController', ['$scope', function($scope) {
    scope = $scope;
    $scope.tripRouteShapeRef = tripRouteShapeRef;
    $scope.refreshTime = refreshTime;
    }
  ]);
  $.getJSON(apiURL + 'api/Buses.json',
  function(data) {
    $("#wait").hide();
    var records = data.RecordSet;
    loadBusData(records);
  });
}
````

If you want me to change, I'll clean it up and won't argue with you.

**Comment by qtrandev** [comment]
I'm trying to get the data back in the GeoJSON format and I see that format is usually like this:
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",

so I'm trying to keep it consistently like that.

**Comment by adam-s** [comment]
That's fine. I don't recommend it because you can pull the data out by adding 5 characters on the client `response.data.`

Here is what it will look like. Is this correct?
````
{
    type: "FeatureCollection",
    features: [{
        type: "Feature",
        geometry: {
            type: "Point",
            coordinates: [
                26.121061, -80.142079
            ]
        },
        properties: {
            lat: 26.121061,
            lon: -80.142079,
            bustime: "2016-03-08T03:43:15.540Z",
            speed: 50,
            deviceid: "5"
        }
    }, {
        type: "Feature",
        geometry: {
            type: "Point",
            coordinates: [
                26.103367, -80.142909
            ]
        },
        properties: {
            lat: 26.103367,
            lon: -80.142909,
            bustime: "2016-03-08T00:39:05.908Z",
            speed: 20,
            deviceid: "1"
        }
    }, {
        type: "Feature",
        geometry: {
            type: "Point",
            coordinates: [
                26.120249, -80.142674
            ]
        },
        properties: {
            lat: 26.120249,
            lon: -80.142674,
            bustime: "2016-03-08T00:38:53.053Z",
            speed: 30,
            deviceid: "1"
        }
    }, {
        type: "Feature",
        geometry: {
            type: "Point",
            coordinates: [
                26.203733, -80.148749
            ]
        },
        properties: {
            lat: 26.203733,
            lon: -80.148749,
            bustime: "2016-03-08T00:38:29.705Z",
            speed: 40,
            deviceid: "4"
        }
    }]
},
````

**Comment by qtrandev** [comment]
Copy the exact format in the issue description. Ex:
```
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          "25.7903",
          "-80.3738"
        ]
```
Not sure of the exact requirements, but the JSON is quoting strings like "type" and "geometry" so follow that.

**Comment by adam-s** [comment]
I have a Chrome app called JSONview which makes JSON look pretty. It is correctly wrapped in quotes. I just copy and pasted the special formatted version.

This is what it looks like without the JSONview:
`{"status":"success","data":{"type":"FeatureCollection","features":[{"type":"Feature","geometry":{"type":"Point","coordinates":[26.121061,-80.142079]},"properties":{"lat":26.121061,"lon":-80.142079,"bustime":"2016-03-08T03:43:15.540Z","speed":50,"deviceid":"5"}},{"type":"Feature","geometry":{"type":"Point","coordinates":[26.103367,-80.142909]},"properties":{"lat":26.103367,"lon":-80.142909,"bustime":"2016-03-08T00:39:05.908Z","speed":20,"deviceid":"1"}},{"type":"Feature","geometry":{"type":"Point","coordinates":[26.120249,-80.142674]},"properties":{"lat":26.120249,"lon":-80.142674,"bustime":"2016-03-08T00:38:53.053Z","speed":30,"deviceid":"1"}},{"type":"Feature","geometry":{"type":"Point","coordinates":[26.203733,-80.148749]},"properties":{"lat":26.203733,"lon":-80.148749,"bustime":"2016-03-08T00:38:29.705Z","speed":40,"deviceid":"4"}}]},"message":null}`

**Comment by adam-s** [comment]
From this issue, I need to discard status and error data and return a pure GEOJSON object. Anything else to add to the /TODO list?

**Comment by qtrandev** [comment]
Sounds good then. I might not even follow the format correctly, but end goal is similar to specified in  https://en.wikipedia.org/wiki/GeoJSON

**Comment by qtrandev** [comment]
I was thinking about your status data, but I really don't know where to put it. If you think it's legal GeoJSON to make it:
{
  "type": "FeatureCollection",
  "status":
  "features": [
then go ahead. If not legal GeoJSON, then don't. I have no idea.

**Comment by adam-s** [comment]
I'm looking at what mapbox.com does and they don't have status and error messages. Since they set the standard for it must be that way. [Here is their example.](https://www.mapbox.com/mapbox.js/example/v1.0.0/geojson-marker-from-url/) The [Mapbox `featurelayer` object has a method `loadUrl`](https://www.mapbox.com/mapbox.js/api/v2.2.1/l-mapbox-featurelayer/#section-featurelayer-loadurl) which expects a GEOJSON object, so that is the way it is done. 

I come from a Drupal background. Those guys at Mapbox started as [Development Seed](https://developmentseed.org/). Now their product is getting a billion views a month on weather.com. They first created the [OpenLayers integration with Drupal](https://www.drupal.org/project/openlayers) which is one of my specialties.

**Comment by qtrandev** [comment]
Follow common standards when possible. I like Mapbox but need to use them more to familiarize with all they do.

**Comment by adam-s** [comment]
What's the best practice? I'm surprised by how difficult it was to find geoJSON information for dynamic responses. Most of the example I could find where static. It would be nice to why something doesn't work. I'm going to add a `metadata` property to the return response following the example of the USGS earthquake feed.

````
{
  "type": "FeatureCollection",
  "metadata": {
    "generated": 1457549576000,
    "url": "http:\/\/earthquake.usgs.gov\/fdsnws\/event\/1\/query?format=geojson&starttime=2014-01-01&endtime=2014-01-02&limit=1",
    "title": "USGS Earthquakes",
    "status": 200,
    "api": "1.5.0",
    "limit": 1,
    "offset": 1,
    "count": 1
  },
  "features": [
    {
      "type": "Feature",
      "properties": {
        "mag": 1.29,
        "place": "10km SSW of Idyllwild-Pine Cove, California",
        "time": 1388620296020,
        "updated": 1388702681220,
        "tz": -480,
        "url": "http:\/\/earthquake.usgs.gov\/earthquakes\/eventpage\/ci11408890",
        "detail": "http:\/\/earthquake.usgs.gov\/fdsnws\/event\/1\/query?eventid=ci11408890&format=geojson",
        "felt": null,
        "cdi": null,
        "mmi": null,
        "alert": null,
        "status": "reviewed",
        "tsunami": 0,
        "sig": 26,
        "net": "ci",
        "code": "11408890",
        "ids": ",ci11408890,",
        "sources": ",ci,",
        "types": ",cap,focal-mechanism,general-link,general-link,geoserve,nearby-cities,origin,phase-data,scitech-link,",
        "nst": 39,
        "dmin": 0.06729,
        "rms": 0.09,
        "gap": 51,
        "magType": "ml",
        "type": "earthquake",
        "title": "M 1.3 - 10km SSW of Idyllwild-Pine Cove, California"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          -116.7776667,
          33.6633333,
          12.39
        ]
      },
      "id": "ci11408890"
    }
  ]
}
````

Source URL:
`http://earthquake.usgs.gov/fdsnws/event/1/query?format=geojson&starttime=2014-01-01&endtime=2014-01-02&limit=1`

**Comment by qtrandev** [comment]
The USGS format looks good. Follow that since I don't have a better reference. Spin up a server soon! I need my GPS Tracker data flowing in!

**Comment by adam-s** [comment]
This is issue is about geoJSON structure. When I copy and paste the output into http://geojsonlint.com/, it is valid geoJSON which renders to the map. Closing issue.
