### ISSUE TITLE
The coordinates array is supposed to be [longitude, latitude]

### ISSUE THREAD

**Issue by adam-s** [adam-s/trolley-tracker#4]
The coordinates array is supposed to be [longitude, latitude], `"coordinates":[ -80.148749
26.203733]`, but for some reason it is being output as [latitude, longitude], `"coordinates":[26.203733,-80.148749]`.

The entire output from the response can be tested for validity at [GeoJSONLint](http://geojsonlint.com/). Also, the specification is found at [geojson.org](http://geojson.org/geojson-spec.html). 

Status and error messages can safely be added inside the geojson object along with type and this can be tested for validity easy enough. I believe it is good to have so in the future developers can give feed back to end users if they wish. If it is valid, it is good practice.

**Comment by qtrandev** [comment]
Man, if I've been using the order of lat/lon wrong, that would suck, but I don't think I'm using the "geometry" section right now. I only use "properties". Are you proposing we change the XML? Go ahead then and reverse those coordinates.

**Comment by adam-s** [comment]
The coordinates array in the response object is rendered [<longitude>, <latitude>]. Structured correctly. Closing issue.
