### ISSUE TITLE
Change deviceId to lowercase deviceid in all sections

### ISSUE THREAD

**Issue by qtrandev** [adam-s/trolley-tracker#6]
README should be updated. Also search for "GET" instead of "POST" copy/paste mistake in README while at it.

**Comment by qtrandev** [comment]
After you change deviceid, push it up to a permanent server - any app name is fine - even keep "trolley-tracker" is ok. I need a server to start sending GPS data to from the tracker.

**Comment by adam-s** [comment]
`deviceId` is now consistent `deviceid`. Closing issue.

**Comment by adam-s** [comment]
Quyen,

My number is (954) 253 -0565

Adam
