### ISSUE TITLE
Where is the front end code for this project?

### ISSUE THREAD

**Issue by adam-s** [adam-s/trolley-tracker#7]
Curious if there is a repository with the front end code for this project?

**Comment by qtrandev** [comment]
Contribute to it here: https://github.com/qtrandev/NodeTrolley

**Comment by qtrandev** [comment]
Live map will be here once CORS issue is fixed: http://qtrandev.github.io/NodeTrolley

**Comment by qtrandev** [comment]
Front end code is now in the client folder. https://github.com/adam-s/trolley-tracker/tree/master/client
